### PR TITLE
change default CI default heap size

### PR DESCRIPTION
**Pull request by humorless**
- [x] change the default heap size as 2G in this PR. 
- [x] add the JVM arguments required by [gceasy](https://gceasy.io/)
- [x] add the log file to the artifacts CI saves.

### CODE REVIEW

**Comment by alysbrooks** [comment]
I think you're OK to merge this. Alternatively, you can add `-J-Xlogc:./gc-log.txt` and add that to the artifacts CI saves.

**Comment by humorless** [comment]
I add some jvm argument required by gceasy because I thought it would be cool if we can use the gc log with [gceasy](https://gceasy.io/), but it is much more [difficult](https://stackoverflow.com/questions/54144713/is-there-a-replacement-for-the-garbage-collection-jvm-args-in-java-11) than I originally thought.

**Comment by alysbrooks** [comment]
@humorless Does gceasy have an example set of configuration flags you could use?

**Comment by alysbrooks** [comment]
@humorless Can you make that change over the next couple of days? It's not urgent but I'm trying finish almost-done PRs. :)

**Comment by plexus** [comment]
Released in [v0.1.175](https://github.com/lambdaisland/regal/releases/tag/v0.1.175)

```clj
[lambdaisland/regal "0.1.175"]                 ;; deps.edn
{lambdaisland/regal {:mvn/version "0.1.175"}}  ;; project.clj
```

**Pull request merged**
