### PR TITLE
Reimplement regex compilation based on spec

### PR DESCRIPTION
**Pull request by DerGuteMoritz**
Allows validation of regal forms and improves extensibility.

Redundant groupings are now avoided in more cases.

Also fixes a bug where quantifiers on multi-character string literals
would be compiled to only apply to the last character (see
corresponding regression test).

Oh yeah, and I've decided to rename `tokens` to `aliases`, the idea being that this could turn into a registry where users could register their own aliases for any regal expression (by qualified key).

Hope it all makes sense!

### CODE REVIEW

**Comment by plexus** [comment]
Hey, thanks for the effort. This is a pretty intrusive change, please give me some time to evaluate it. I would like support for regal _in spec_, but i was planning to keep the spec dependency optional (the way test.check is optional) since it's still beta.

I'm not saying no on this, it does bring some nice benefits, but I need to play with it to make sure I can maintain it and that this is the direction I want regal to go.

**Comment by DerGuteMoritz** [comment]
Hi Arne,

sure thing, totally your call, of course :-) IMHO a dependency on spec isn't too bad a trade-off compared to the benefits it provides, especially in parsing-heavy DSL contexts like this. And since clojure.core already pulls it in anyway... :-)

Can you explain what you mean by supporting regal in spec? As in compiling to spec's regex forms?

In any case, let me know if anything is unclear and happy hammock time!

**Comment by plexus** [comment]
The idea is to have spec objects based on regal that validate based on the regex and generate based on the gens, and that compose.

Say (hypothetical API) you have `regal-spec` to create such a spec

```
(s/def ::word (regal-spec [:+ [:range "a" "z"]]))
(s/def ::sentence (regal-spec [:cat [:* [:cat ::word " "]] ::word]))

(s/valid? ::sentence "hello world")
```

**Comment by plexus** [comment]
hey @DerGuteMoritz, thanks again for all the effort. I hate to say this but I don't want to continue down this road. It doubles the amount of code, and it does it in a way that I think is a lot harder to follow and that I'm not comfortable maintaining.

I do think there are valuable things here, the test for the edge case you added should definitely go in. I also do think having a spec for valid regal forms is useful, not the least for our own generative testing, but I don't think using that for parsing is the way to go.

If it's ok with you I'd like to merge this to have at least those bits, to make sure you get credit, and to preserve the history of this exploration, then move the specs to `lambdaisland.regal.spec-alpha`, and revert `lambdaisland.regal`, then continue from there.

**Comment by DerGuteMoritz** [comment]
Hey Arne,

sure, I can understand your decision, no hard feelings! I would be up for preparing fresh patches for those edge cases and the spec-only namespace. No need to preserve this approach in the mainline history IMHO, the PR and branch will stick around anyway :+1: So feel free to close this one if you're fine with that!

Cheers
Moritz

**Comment by plexus** [comment]
Replaced by #9 and #10.

**Pull request closed without merging**
